apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: padm2regler
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  vault:
    enabled: true
    paths:
      - kvPath: /azuread/data/prod/creds/padm2regler
        mountPath: /secrets/azuread/padm2regler
      - kvPath: serviceuser/data/prod/srvpadm2regler
        mountPath: /secrets/serviceuser
  webproxy: true
  ingresses:
    - "https://padm2regler.nais.adeo.local"
  env:
    - name: HELSENETTPROXY_ID
      value: b813133d-82b8-46ef-be96-3b903ea6c048
    - name: AADACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navno.onmicrosoft.com/oauth2/token